apiVersion: v1
kind: Namespace
metadata:
  name: edenschool-production
  labels:
    name: edenschool-production
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: edenschool-api-minecraftrcon-configmap
  namespace: edenschool-production
data:
  RCON_HOST: "edenschool-minecraft-service"
  RCON_PORT: "25575"
---
apiVersion: v1
kind: Secret
metadata:
  name: edenschool-api-minecraftrcon-secret
  namespace: edenschool-production
type: Opaque
data:
  RCON_PASSWORD: "c2VjcmV0Cg=="
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: edenschool-api-minecraftrcon-deployment
  namespace: edenschool-production
  labels:
    app: edenschool-api-minecraftrcon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: edenschool-api-minecraftrcon
  template:
    metadata:
      labels:
        app: edenschool-api-minecraftrcon
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: api-minecraftrcon-nodejs
          image: "ghcr.io/lloyet/es-minecraftrcon-nodejs:1.0.0"
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: edenschool-api-minecraftrcon-configmap
          env:
            - name: RCON_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: edenschool-api-minecraftrcon-secret
                  key: RCON_PASSWORD
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: "128m"
              memory: "256Mi"
            limits:
              cpu: "256m"
              memory: "512Mi"
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 60